version: '3.8'

services:
  postgres-clinica:
    image: postgres:15-alpine
    container_name: postgres-clinica-sw2
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "12345"
      POSTGRES_DB: p2_sw2_nest
    ports:
      - "5432:5432"
    volumes:
      - postgres_clinica_data:/var/lib/postgresql/data

  api-clinica:
    image: willxd123/api-clinica:latest # <-- Imagen desde Docker Hub
    container_name: api-clinica-sw2
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      # Sobreescribimos el DATABASE_HOST para que apunte al contenedor de la BD en lugar de localhost
      - DATABASE_HOST=postgres-clinica
      - N8N_API_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI0Zjg2NGE3ZC0xMzI2LTQ4N2EtYjgyNy05N2Q0ZTZlNzZiZDAiLCJpc3MiOiJuOG4iLCJhdWQiOiJwdWJsaWMtYXBpIiwianRpIjoiZTNjNmU5YjEtZGIzMi00ZDkxLWFmNmMtYzAyZDE5MDYwNWY0IiwiaWF0IjoxNzgxMTIzMDEwLCJleHAiOjE3ODYyNDgwMDB9.kkUa4fE3TdoDV4CpbxnO39y5on2Yptzn64wjYIm5z-I
      - GESTION_ADMINISTRATIVA_URL=http://52.180.69.59:3001/graphql
    depends_on:
      - postgres-clinica

volumes:
  postgres_clinica_data:
